name: distcheck

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "README.md", "TODO.md" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "README.md", "TODO.md" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
